version: "{build}-{branch}"

branches:
  except:
    - gh-pages

init:
  - ps: $PSVersionTable.keys |% {"$_ $($PSVersionTable[$_])"}
  - ps: (get-psprovider 'FileSystem').Home = $(pwd)

build: off

install:
- powershell .\build.ps1

test_script:
  - ps: get-module
  - ps: $(get-location).path
  - ps: "& .\\test.ps1"
